insert into `info_tracker`.`website` (title,url,score)values(An account of a serious medical emergency on a transoceanic flight,https://news.ycombinator.com/item?id=12417290,789);
insert into `info_tracker`.`website` (title,url,score)values(How to Tell a Mother Her Child Is Dead,https://news.ycombinator.com/item?id=12421687,574);
insert into `info_tracker`.`website` (title,url,score)values(500 Byte Images: The Haiku Vector Icon Format,https://news.ycombinator.com/item?id=12420763,232);
insert into `info_tracker`.`website` (title,url,score)values(FLAC Support in Firefox 51,https://news.ycombinator.com/item?id=12422891,216);
insert into `info_tracker`.`website` (title,url,score)values(People in Los Angeles Are Getting Rid Of Their Cars,https://news.ycombinator.com/item?id=12420147,209);
insert into `info_tracker`.`website` (title,url,score)values(Skypeopensource2 – Skype client based on reversing Skype 5.5,https://news.ycombinator.com/item?id=12423331,191);
insert into `info_tracker`.`website` (title,url,score)values(“We have been experiencing a catastrophic DDoS attack”,https://news.ycombinator.com/item?id=12422124,171);
insert into `info_tracker`.`website` (title,url,score)values(A Fighter Pilot’s Guide to Surviving on the Roads (2012) [pdf],https://news.ycombinator.com/item?id=12422378,167);
insert into `info_tracker`.`website` (title,url,score)values(Richard Stallman: Online Publishers Should Let Readers Pay Anonymously,https://news.ycombinator.com/item?id=12423371,161);
insert into `info_tracker`.`website` (title,url,score)values(The neurology of self-awareness,https://news.ycombinator.com/item?id=12420811,159);
insert into `info_tracker`.`website` (title,url,score)values(Fresh IDE v2.3.0 has been released.,https://www.reddit.com/r/programming/comments/5134ur/fresh_ide_v230_has_been_released/,99);
insert into `info_tracker`.`website` (title,url,score)values(I made a network graph of programming languages and compilers,https://www.reddit.com/r/programming/comments/510lti/i_made_a_network_graph_of_programming_languages/,104);
insert into `info_tracker`.`website` (title,url,score)values(So You Want to be a Functional Programmer (Part 1),https://www.reddit.com/r/programming/comments/50zpin/so_you_want_to_be_a_functional_programmer_part_1/,98);
insert into `info_tracker`.`website` (title,url,score)values(500 Byte Images: The Haiku Vector Icon Format,https://www.reddit.com/r/programming/comments/513u35/500_byte_images_the_haiku_vector_icon_format/,186);
insert into `info_tracker`.`website` (title,url,score)values(Results of the 2016 Nim Community Survey,https://www.reddit.com/r/programming/comments/510jgh/results_of_the_2016_nim_community_survey/,90);
insert into `info_tracker`.`website` (title,url,score)values(PEP 530 -- Asynchronous Comprehensions,https://www.reddit.com/r/programming/comments/511i0j/pep_530_asynchronous_comprehensions/,87);
insert into `info_tracker`.`website` (title,url,score)values(Gambas 3.9.0 is out! Gambas is a free development environment and a full powerful development platform based on a Basic interpreter with object extensions, as easy as Visual Basic?.,https://www.reddit.com/r/programming/comments/513l8b/gambas_390_is_out_gambas_is_a_free_development/,49);
insert into `info_tracker`.`website` (title,url,score)values(SPIR-V Compression,https://www.reddit.com/r/programming/comments/50zh0c/spirv_compression/,36);
insert into `info_tracker`.`website` (title,url,score)values(This Website is Basically AMP HTML,https://www.reddit.com/r/programming/comments/51049h/this_website_is_basically_amp_html/,38);
insert into `info_tracker`.`website` (title,url,score)values(APICombo - API Testing and Monitoring in the easiest way,https://www.reddit.com/r/programming/comments/5127hj/apicombo_api_testing_and_monitoring_in_the/,8);
insert into `info_tracker`.`website` (title,url,score)values(5439,I Got Scammed By A Silicon Valley Startup,https://medium.com/p/i-got-scammed-by-a-silicon-valley-startup-574ced8acdff);
insert into `info_tracker`.`website` (title,url,score)values(584,A verdade sobre Bel Pesce,https://medium.com/p/a-verdade-sobre-bel-pesce-82c706e16b4a);
insert into `info_tracker`.`website` (title,url,score)values(1139,Cognitive bias cheat sheet,https://medium.com/p/cognitive-bias-cheat-sheet-55a472476b18);
insert into `info_tracker`.`website` (title,url,score)values(354,Why I Am Giving Up Teaching,https://medium.com/p/why-i-am-giving-up-teaching-bc3ec2071c80);
insert into `info_tracker`.`website` (title,url,score)values(358,How not to bomb your offer negotiation,https://medium.com/p/how-not-to-bomb-your-offer-negotiation-c46bb9bc7dea);
insert into `info_tracker`.`website` (title,url,score)values(524,8 Ways Billionaires and Elite Athletes Perform at the Highest Level,https://medium.com/p/8-ways-billionaires-and-elite-athletes-perform-at-the-highest-level-cd7f97082f5e);
insert into `info_tracker`.`website` (title,url,score)values(2938,How I Used & Abused My Tesla — What a Tesla looks like after 100,000 Miles, a 48 State Road trip…,https://medium.com/p/how-i-used-abused-my-tesla-what-a-tesla-looks-like-after-100-000-miles-a-48-state-road-trip-6b6ae66b3c10);
insert into `info_tracker`.`website` (title,url,score)values(553,7 Productivity Apps That Shave 10 Hours Off Your Work Week,https://medium.com/p/7-productivity-apps-that-shave-10-hours-off-your-work-week-634604304763);
insert into `info_tracker`.`website` (title,url,score)values(500,0 to $640M: Non-obvious Lessons Learned at BrightRoll,https://medium.com/p/0-to-640m-non-obvious-lessons-learned-at-brightroll-b6b3eb4086ac);
insert into `info_tracker`.`website` (title,url,score)values(561,How to read to learn and exercise your brain,https://medium.com/p/how-to-read-to-learn-and-exercise-your-brain-df8310785239);
insert into `info_tracker`.`website` (title,url,score)values(LetsVenture: Discover &amp; invest in startups,https://www.producthunt.com/tech/letsventure-2,119);
insert into `info_tracker`.`website` (title,url,score)values(Stocky: Free photo, video, graphics &amp; music for commercial use.,https://www.producthunt.com/tech/stocky,70);
insert into `info_tracker`.`website` (title,url,score)values(JAYC.audio: Youtube converter, simple, fast &amp; ad-free,https://www.producthunt.com/tech/jayc-audio,44);
insert into `info_tracker`.`website` (title,url,score)values(Burfi 2.0: A simplest way to take notes without leaving your browser.,https://www.producthunt.com/tech/burfi-2-0,35);
insert into `info_tracker`.`website` (title,url,score)values(people.ai: Know what your sales team is up to,https://www.producthunt.com/tech/people-ai,37);
insert into `info_tracker`.`website` (title,url,score)values(Hello Tech Pros: Interview Players For Your D&amp;D Campaign: By playing board games,https://www.producthunt.com/podcasts/hello-tech-pros-interview-players-for-your-d-d-campaign,3);
insert into `info_tracker`.`website` (title,url,score)values(Hotkey: Simple yet powerful lists with a keyboard only interface,https://www.producthunt.com/tech/hotkey,23);
insert into `info_tracker`.`website` (title,url,score)values(Get Moving: The app that motivates you to sit less and stand more.,https://www.producthunt.com/tech/get-moving,20);
insert into `info_tracker`.`website` (title,url,score)values(Racefully: Run with friends wherever they are!,https://www.producthunt.com/tech/racefully,23);
insert into `info_tracker`.`website` (title,url,score)values(Timezoner: Time zone calculator bot for Slack,https://www.producthunt.com/tech/timezoner,2);
insert into `info_tracker`.`website` (title,url,score)values(ElemeFE/element: Desktop UI elements for Vue.js 2.0,https://github.com/ElemeFE/element,201);
insert into `info_tracker`.`website` (title,url,score)values(tmrts/go-patterns: A curated list of Go patterns and idioms,https://github.com/tmrts/go-patterns,200);
insert into `info_tracker`.`website` (title,url,score)values(facebook/zstd: Zstandard - Fast real-time compression algorithm,https://github.com/facebook/zstd,168);
insert into `info_tracker`.`website` (title,url,score)values(xcatliu/mobi.css: A lightweight, flexible css framework that focus on mobile.,https://github.com/xcatliu/mobi.css,152);
insert into `info_tracker`.`website` (title,url,score)values(david-gpu/srez: Image super-resolution through deep learning,https://github.com/david-gpu/srez,138);
insert into `info_tracker`.`website` (title,url,score)values(heynickc/awesome-ddd: A curated list of Domain-Driven Design (DDD), Command Query Responsibility Segregation (CQRS), Event Sourcing, and Event Storming resources,https://github.com/heynickc/awesome-ddd,138);
insert into `info_tracker`.`website` (title,url,score)values(gridcontrol/gridcontrol: Networked Process Manager to execute functions in a Computer Grid,https://github.com/gridcontrol/gridcontrol,131);
insert into `info_tracker`.`website` (title,url,score)values(waud/waud: Web Audio Library,https://github.com/waud/waud,122);
insert into `info_tracker`.`website` (title,url,score)values(brillout/awesome-react-components: Catalog of React components / libraries,https://github.com/brillout/awesome-react-components,116);
insert into `info_tracker`.`website` (title,url,score)values(VctrySam/whatsapp: WhatsApp in React Native,https://github.com/VctrySam/whatsapp,113);
insert into `info_tracker`.`website` (title,url,score)values(现在应不应该回国？,https://www.v2ex.com/t/303767#reply76,76);
insert into `info_tracker`.`website` (title,url,score)values(两万毫安时的移动电源选什么好,https://www.v2ex.com/t/303778#reply44,44);
insert into `info_tracker`.`website` (title,url,score)values(请问： win10 还需要安装杀毒软件和安全卫士之类的软件吗？自带的那个怎么样？,https://www.v2ex.com/t/303813#reply39,39);
insert into `info_tracker`.`website` (title,url,score)values(求三万以内笔记本推荐,https://www.v2ex.com/t/303862#reply33,33);
insert into `info_tracker`.`website` (title,url,score)values(三大运营商，有没有只能上网，打电话，收发短信的套餐。,https://www.v2ex.com/t/303842#reply26,26);
insert into `info_tracker`.`website` (title,url,score)values(你们的自动签到脚本还好吗？,https://www.v2ex.com/t/303768#reply25,25);
insert into `info_tracker`.`website` (title,url,score)values(BGmi，用命令行追番,https://www.v2ex.com/t/303853#reply19,19);
insert into `info_tracker`.`website` (title,url,score)values(这个游戏大家最好成绩是多少？我是 3800 多,https://www.v2ex.com/t/303766#reply18,18);
insert into `info_tracker`.`website` (title,url,score)values(最近公司有做一套 OA 系统的需求，请问下大家， python 有没有比 django 更合适的框架？,https://www.v2ex.com/t/303865#reply18,18);
insert into `info_tracker`.`website` (title,url,score)values(我讨厌自动补齐空格的原因,https://www.v2ex.com/t/303784#reply17,17);
